### ISSUE TITLE
TZ1 payouts are failing (and some KT1)

### ISSUE THREAD

**Issue by bb4L** [tezos-reward-distributor-organization/tezos-reward-distributor#567]
**Describe the bug**
The payouts for TZ1 addresses aren't working. (in the below information / logs i removed the actual amount and address with placeholders
KT1 addresses seem to work mostly, there are also some which are reported with:

```
ADDRESS ,D, AMOUNT ,None,4,0,0,
```

The TZ1 in the file `failed/455.csv.BUSY` have the following structure: (the file keeps the `BUSY` extension)

```
ADDRESS ,D, AMOUNT ,None,0,0,1185,
```

It looks as if the `consumer0` stopped / crashed with the following log:
(at least there isn't any newer output from the consumer, only from the `producer_retry_fail`)
```
2022-03-12 19:38:44,645 - consumer0 - ERROR - Error at reward payment
Traceback (most recent call last):
  File "/app/src/pay/payment_consumer.py", line 159, in _consume_batch
    ) = batch_payer.pay(payment_items, dry_run=self.dry_run)
  File "/app/src/pay/batch_payer.py", line 350, in pay
    payment_log, attempt = self.pay_single_batch(
  File "/app/src/pay/batch_payer.py", line 420, in pay_single_batch
    if dry_run or status.is_fail():
AttributeError: 'NoneType' object has no attribute 'is_fail'
```

**To Reproduce**

1. setup tezos-reward-distributor and let it run
1. check `.csv` file

**Expected behavior**
Payouts should be paid and / or in the csv should be the reason why it wasn't paid

**Screenshots**

**Environment**
- Docker build from a3290ca43f99595b84072f1bf75a604e22b1593e
- local tezos http signer (version 12.0)
- configuration (without the addresses)
  ```yaml
  rewards_type: actual
  service_fee: 10
  founders_map:
  {
    # This map is optional if founders do not want to be paid from service fees, in this case, service fee remains in baking balance.
  }
  owners_map:
  {
    # This map is optional if owners do not want to be paid for baking rewards, in this case, baking rewards remain in baking 
  balance.
  }
  specials_map: 
  {
  }
  supporters_set:
  {
    # Supporters are not charged with a service fee. Founders and balance owners are natural supporters, they are not needed to be added.
  }
  min_delegation_amt: 1
  reactivate_zeroed: False # reactivates accounts with zero balance
  delegator_pays_xfer_fee: True # If set to false, the transfer fee for each payment is paid by the delegate
  delegator_pays_ra_fee: True #  If True, the burn fee is subtracted from the reward payment (ie: delegate pays)
  rules_map:
    ...
    mindelegation: TOB
  pay_denunciation_rewards: False
  ```

- Chain mainnet
- actual command used: `"-V=on","-A=https://OUR_NODE", "-P=tzkt","-E=http://127.0.0.1:6732", "-Dp", "-O=90", "-C=455",`
- Operating system / system specification: linux server running docker-compose v1.29.2

**Additional context**
if more information is needed feel free to ask

if this issue should be split up into multiple feel free to do so / tell me which parts should be split up
